name: CustomLevelKB
main: SVega9848\CustomLevelKB\Core\Main
version: 0.2.0
api: 5.0.0
load: POSTWORLD
author: SVega
description: Customize your servers kb!

permissions:
  customlevelkb.cmd:
    description: CustomLevelKB command permission
    default: op

